
services:
  db:
    image: mysql:8.0-oracle
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: emp
      MYSQL_USER: localdev123456
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - my-external-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    networks:
      - my-external-network
    ports:
      - 8081:80
#  app:
#    container_name: app
#    image: management-user
#    ports:
#      - "8080:8080"
#    networks:
#        - my-external-network
#    environment:
#      - "SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/emp"
#      - "SPRING_DATASOURCE_USERNAME=localdev123456" # Replace 'your_mysql_user' with the same name you used for MYSQL_USER in the db service.
#      - "SPRING_DATASOURCE_PASSWORD=123456" # Replace 'your_mysql_password' with the same name you used for MYSQL_PASSWORD in the db service.
#    depends_on:
#      - db


volumes:
  dbdata:

networks:
  my-external-network:
    name: my-external-network
    external: true